[package]
name = "launch-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre.workspace = true
itertools = "0.12.1"
launch-format = { version = "0.1.0", path = "../launch-format" }
launch-subst = { version = "0.1.0", path = "../launch-subst" }
quick-xml = { version = "0.36.1", features = ["serialize"] }
serde_yaml = "0.9.34"

[dev-dependencies]
clap = { version = "4.5.1", features = ["derive"] }
itertools = "0.12.1"
